##########################################################
##################  所有profile共有的配置  #################
##########################################################
sequence:
  workerId: 0
###################  项目启动端口  ###################
server:
  port: 8080
spring:
  application:
    name: aims-service
  profiles:
    #读取不同环境的配置
     #日志分为：log_dev(只打印到控制台)、log_prod(打印到控制台、输出到日志文件)
    active: datasource,dev,log_prod
  aop:
    proxy-target-class: true #false为启用jdk默认动态代理,true为cglib动态代理