##########################################################
###################  开发环境的profile  ###################
##########################################################
#spring:
#  profiles: dev
#  datasource:
#    druid:
#      type: com.alibaba.druid.pool.DruidDataSource
#      url: jdbc:mysql://47.103.105.200:3306/icu?serverTimezone=GMT%2B8&useUnicode=true&characterEncoding=utf8&useSSL=false&zeroDateTimeBehavior=CONVERT_TO_NULL
#      username: root
#      password: Pass@word!123
#      driverClassName: com.mysql.cj.jdbc.Driver


spring:
  profiles: dev
  datasource:
    druid:
      type: com.alibaba.druid.pool.DruidDataSource
      url: jdbc:mysql://127.0.0.1:3306/operation_scheduling?serverTimezone=GMT%2B8&useUnicode=true&characterEncoding=utf8&useSSL=false&zeroDateTimeBehavior=CONVERT_TO_NULL
      username: root
      password: root
      driverClassName: com.mysql.cj.jdbc.Driver

custom:
  profiles: dev
  datasource:
    druid:
      type: com.alibaba.druid.pool.DruidDataSource
      names: db1,db2
      db1:
        driverClassName: com.mysql.cj.jdbc.Driver
        url: jdbc:mysql://47.103.105.200:3306/his?serverTimezone=GMT%2B8&useUnicode=true&characterEncoding=utf8&useSSL=false&zeroDateTimeBehavior=CONVERT_TO_NULL
        username: root
        password: Pass@word!123
      db2:
        driverClassName: com.mysql.cj.jdbc.Driver
        url: jdbc:mysql://47.103.105.200:3306/icu?serverTimezone=GMT%2B8&useUnicode=true&characterEncoding=utf8&useSSL=false&zeroDateTimeBehavior=CONVERT_TO_NULL
        username: root
        password: Pass@word!123

logging:
  level.root: info
  level.com.icu: debug

#jdbc:mysql://127.0.0.1:3306/icu?serverTimezone=GMT%2B8&useUnicode=true&characterEncoding=utf8&useSSL=false&zeroDateTimeBehavior=CONVERT_TO_NULL
